### ISSUE TITLE
建议打开 # s.ios.deployment_target = "5.0"

### ISSUE THREAD

**Issue by tounaobun** [maltsugar/RollingNotice#10]
/Users/apple/app-ios/anxldriver/Pods/RollingNotice/RollingNotice/GYRollingNoticeView/GYRollingNoticeView.m:197:5: Cannot create __weak reference because the current deployment target does not support weak references

建议在podspec文件中把 s.ios.deployment_target = "5.0" 打开, 去掉#

**Comment by maltsugar** [comment]
好了 感谢提出 @tounaobun
