### ISSUE TITLE
demo有问题，push pop回来首页文字不显示了

### ISSUE THREAD

**Issue by Vutumn** [maltsugar/RollingNotice#11]

**Comment by maltsugar** [comment]
兄弟  故意的啊，你看代码啊  回来时只开启第一个，第二个没开启
![image](https://user-images.githubusercontent.com/8554146/50671346-4da7b800-100c-11e9-8b45-2493c4743ab1.png)

**Comment by Vutumn** [comment]
好的老哥，我的问题。没注意看代码。

**Comment by maltsugar** [comment]
你注册cell了吗

**Comment by Vutumn** [comment]
注册了

**Comment by Vutumn** [comment]
noticeView.delegate = self
        noticeView.dataSource = self
        noticeView.register(GYNoticeViewCell.self, forCellReuseIdentifier: "GYNoticeViewCell")

**Comment by maltsugar** [comment]
稍等  现在有点忙 你先自己查查原因
