### ISSUE TITLE
外部通过currentIndex属性从数组中获取值时可能会越界

### ISSUE THREAD

**Issue by xygkevin** [maltsugar/RollingNotice#17]
定时器任务中currentIndex++造成的，建议优化

**Comment by maltsugar** [comment]
一个cell 和 多个cell 我都试过了 currentIndex 并没有问题

**Comment by xygkevin** [comment]
![image](https://user-images.githubusercontent.com/19592642/79328896-5d20eb00-7f49-11ea-99e7-b74493467b63.png)

**Comment by xygkevin** [comment]
我看了你的代码，你在内部使用currentIndex的时候做了纠正处理，但是并没有针对外部调用的时候考虑临界值的问题

**Comment by xygkevin** [comment]
把滚动间隔时间设置的大一点，就容易复现了

**Comment by maltsugar** [comment]
已修复，非常感谢
