### ISSUE TITLE
请问停止后如何开启

### ISSUE THREAD

**Issue by YongHuiBai** [maltsugar/RollingNotice#2]
请问停止后如何开启

**Comment by maltsugar** [comment]
reloadDataAndStartRoll就行了啊
如果你这个页面是在根视图，可以不用stop，因为根视图不需要释放。 让在合适的地方stop，只是为了防止不释放

**Comment by YongHuiBai** [comment]
一直不释放不占用CUP吗?

**Comment by maltsugar** [comment]
这一点可以忽略吧，主要是内存不能浪费，不释放就成了野指针
