### ISSUE TITLE
点击事件应该暴露出来，或者至少把点击的坐标点传递出来

### ISSUE THREAD

**Issue by medivh-xiong** [maltsugar/RollingNotice#6]
现在点击事件是整体，有时候碰到需求点上面执行a，点下面的文字执行B，没法实现该功能

**Comment by maltsugar** [comment]
这个跟UITableViewCell一样，你有怎样的需求都可以满足啊。
你这种情况只需要，自定义一个Cell，随便你加几个按钮，代理传到控制器就行啊，这个框架特点就是灵活，不变应万变😓

**Comment by medivh-xiong** [comment]
我这边情况跟你不太一样，我是每个文字都对应一个URL，放2个按钮你没法确定你点击的是哪个index的值，虽然可以用文字去遍历整个数组去获取，但是感觉这种写法有点傻

**Comment by medivh-xiong** [comment]
额，我想复杂了

**Comment by maltsugar** [comment]
😁感觉好用的话希望多多支持，谢谢
