### ISSUE TITLE
循环引用

### ISSUE THREAD

**Issue by chenfengxiaoxixi** [maltsugar/RollingNotice#8]
UIView animate动画block内有循环引用的情况

**Comment by maltsugar** [comment]
UIView block动画是单向引用的，不会造成循环引用。你只要页面消失时停止timer，你会发现这个类会走dealloc方法，说明不存在循环引用问题。

具体可以参考[循环引用](https://www.jianshu.com/p/89bb949302af)，[使用系统的某些block api（如UIView的block版本写动画时），是否也考虑引用循环问题？](https://www.jianshu.com/p/0d145fc72d3d)，欢迎交流
